### ISSUE TITLE
Test passing on rerun is still reported as failed

### ISSUE THREAD

**Issue by hdesai-dave** [billylam/wdio-wdiov5testrail-reporter#11] opened 2022-05-18 00:15 UTC
Have looked at the junit reporter log file and the test should have been marked as passed since the test failed on rerun, but i still see the test case having 2 results:

1) when test actually failed and with the correct error
2) failed with following reason: This test was marked as 'Failed'.

Junit reporter log has:
  
"testsuite name="Withdraw_funds_to_debit_card" timestamp="2022-05-17T14:55:58" time="41.663" tests="2" failures="0" errors="0" skipped="0" "

**Comment by hdesai-dave** [comment] 2022-05-18 00:16
My Reporter setting:

[
      'spec',
      [
        'junit',
        {
          outputDir: './report/',
        },
      ],
      [
        'wdiov5testrail',
        {
          domain: '****.testrail.io',
          username: process.env.TESTRAIL_USERNAME,
          password: process.env.TESTRAIL_PASSWORD,
          projectId: 1,
          suiteId: 1,
          strictCaseMatching: false,
          title: process.env.BRANCH_NAME || 'Test',
        },
      ],
    ];

**Comment by billylam** [comment] 2022-05-18 18:33
I'm not sure what the issue is.  If it's an issue with junit reporter you'd need to report it to the appropriate repo, https://github.com/webdriverio/webdriverio.

If this is an issue with this testrail reporter, it's working for me as I intended it to.  If a rerun fails and a runId is passed, a previously passing case is marked as failed and vice versa.

**Comment by billylam** [comment] 2022-05-18 18:36
<img width="1006" alt="Screen Shot 2022-05-18 at 11 34 56 AM" src="https://user-images.githubusercontent.com/3700437/169119881-1fae34f4-e94c-49e6-b21c-819519abbfec.png">

**Comment by hdesai-dave** [comment] 2022-05-18 18:58
@billylam  in my case re run passed. I was just showing you junit reporter output to prove that the test should have been marked as passed but it is reported as false.

**Comment by hdesai-dave** [comment] 2022-05-18 19:06
We don’t pass the run id and let the reporter create a new run. I do get the rerun results posted in testrail but it’s marking the test as failed instead of Pass.

**Comment by billylam** [comment] 2022-05-18 20:30
Okay I think I see - you retry a test twice, the first time it fails, the second time it passes, but the reporter fails the test in testrail.

When I try this test case with a minimal case, it works for me, though:
```

describe('test', function () {
  let willPass = false;
  this.retries(2);
  it(`C1592888 sample test`, function () {
    if (willPass === false) {
      willPass = true;
      assert.isTrue(false);
    } else {
      assert.isTrue(true);
    }
  });
});

```

The result is one entry in testrail
<img width="622" alt="image" src="https://user-images.githubusercontent.com/3700437/169150164-f86662f7-5f5a-4ed0-8a1c-822b5cbaa2c3.png">


Can you let me know if this sounds the same as your case?
If so it would also help to know your webdriverio version, and whether you are using mocha, jasmine, cucumber or some combination.  And how you are retrying if not as the above.

**Comment by hdesai-dave** [comment] 2022-05-18 21:26
WDIO packages:

    "@wdio/appium-service": "^6.1.16",
    "@wdio/browserstack-service": "^7.16.13",
    "@wdio/cli": "^6.3.3",
    "@wdio/junit-reporter": "^6.3.4",
    "@wdio/local-runner": "^6.3.3",
    "@wdio/mocha-framework": "^6.3.0",
    "@wdio/spec-reporter": "^6.3.0",
    "@wdio/sync": "^6.3.3"

I use mocha bdd style tests.
I use wdio capabilities like below to retry failing test:

  specFileRetries: 1,
  // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
  specFileRetriesDeferred: true,

Get 2 Results as below:
<img width="1235" alt="Screen Shot 2022-05-18 at 2 24 51 PM" src="https://user-images.githubusercontent.com/83988558/169158523-d47feba1-38a7-4f28-bd95-bd90fcf8ea2c.png">

Looking at the time stamps, it seems when retry is triggered and deferred for later due to   specFileRetriesDeferred: true,
 result in testrail gets reported as failed or maybe all results are reported at the same time so timestamp is not much useful here.

**Comment by hdesai-dave** [comment] 2022-05-18 21:33
FYI, when the test fails twice both failed results are updated correctly in testrail.

**Comment by billylam** [comment] 2022-05-18 22:22
Thanks.  The issue is that the reporter isn't differentiating from when two different tests have the same testrail id, versus when the same test runs twice.  In the first case, if one test fails, the entire case fails, which explains what you're seeing. Hopefully will have a fix within a few days.

**Comment by billylam** [comment] 2022-05-19 05:08
Try 1.0.31 and let me know if you are still seeing issues.

**Closed as completed by billylam** 2022-05-19 05:08 UTC

**Comment by hdesai-dave** [comment] 2022-05-19 05:10
> Try 1.0.31 and let me know if you are still seeing issues.

Will let you know how our nightly runs go.

**Comment by billylam** [comment] 2022-05-19 16:58
Please retry with 1.0.32 instead.
